version: '3.7'

services:

  test-e2e:
    image: node:14-alpine
    environment: 
      NODE_ENV: test
      APP_PORT: 3000
      APP_SECRET: shhh
      MONGO_URI: mongodb://mongodb:27017/boticario_test
      MONGO_RETRY_ATTEMPTS: 3
      MONGO_RETRY_DELAY: 2500
      MONGO_CONNECTION_NAME: macmini
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BOTICARIO_HOST: https://mdaqk8ek5j.execute-api.us-east-1.amazonaws.com/v1
      BOTICARIO_TOKEN: ZXPURQOARHiMc6Y0flhRC1LVlZQVFRnm
    depends_on: 
      - mongodb
      - redis
    command: >
      /bin/sh -c "
        yarn test:e2e test/purchase.e2e-spec.ts
      "

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  redis:
    image: "redis:6.2"
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data_container: