version: '3'

services:

  gb-nest:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
  
  mongodb:
    image: mongo:4.2
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  redis:
    image: redis
    expose:
      - 6379

volumes:
  mongodb_data_container: